// 
// All of the code is generated by ChatGPT
// 

#include <Arduino.h>
#include <WiFi.h>

// =====================================================
// Wi-Fi and TV settings
// =====================================================

const char* WIFI_SSID = "WIFI NAME";
const char* WIFI_PASSWORD = "WIFI PASSWORD";

// Give the TV a fixed DHCP reservation in the router
// so that this address does not change.
IPAddress TV_IP(192, 168, 0, 90);

// The Samsung TV responds on at least one of these ports
// while it is powered on.
constexpr uint16_t TV_PORTS[] = {8001, 8002};

// =====================================================
// GPIO pins
// =====================================================

// Drives the optocoupler connected across the
// soundbar's physical power button.
constexpr uint8_t POWER_BUTTON_PIN = 0;

// Reads the divided voltage from the soundbar USB port.
// HIGH = soundbar on
// LOW  = soundbar off
constexpr uint8_t SOUNDBAR_STATUS_PIN = 1;

// =====================================================
// Timing settings
// =====================================================

// Check the TV every two seconds.
constexpr unsigned long TV_CHECK_INTERVAL_MS = 1000;

// Duration of the simulated button press.
constexpr unsigned long BUTTON_PRESS_DURATION_MS = 200;

// Minimum delay between power-button presses.
// This prevents repeated toggling while the soundbar starts or stops.
constexpr unsigned long POWER_RETRY_INTERVAL_MS = 15000;

// Maximum time allowed for each TCP connection attempt.
constexpr int TV_CONNECT_TIMEOUT_MS = 700;

// Number of consecutive successful checks required
// before the TV is considered on.
constexpr uint8_t REQUIRED_ON_DETECTIONS = 2;

// Number of consecutive failed checks required
// before the TV is considered off.
constexpr uint8_t REQUIRED_OFF_DETECTIONS = 3;

// Time allowed for the soundbar status pin to confirm
// that an automatic start was successful.
constexpr unsigned long START_CONFIRM_TIMEOUT_MS = 10000;

// How often the ESP tries to reconnect to Wi-Fi.
constexpr unsigned long WIFI_RECONNECT_INTERVAL_MS = 10000;

// =====================================================
// Runtime state
// =====================================================

unsigned long lastTvCheckTime = 0;
unsigned long lastPowerButtonPressTime = 0;
unsigned long lastWifiReconnectAttempt = 0;
unsigned long automaticStartAttemptTime = 0;

uint8_t successfulTvChecks = 0;
uint8_t failedTvChecks = 0;

// We do not act until the first reliable TV state
// has been determined.
bool tvStatusKnown = false;
bool tvIsOn = false;

// True only when the ESP started the soundbar
// specifically because the TV was on.
//
// A manually started soundbar will therefore remain unmanaged.
bool soundbarManagedByTv = false;

// True while waiting for GPIO1 to confirm that
// an automatic power-on attempt worked.
bool automaticStartPending = false;

// =====================================================
// Soundbar functions
// =====================================================

bool soundbarIsOn()
{
    return digitalRead(SOUNDBAR_STATUS_PIN) == HIGH;
}

void pressSoundbarPowerButton(const char* reason)
{
    Serial.print("Pressing soundbar power button: ");
    Serial.println(reason);

    // Turn on the optocoupler LED.
    digitalWrite(POWER_BUTTON_PIN, HIGH);

    delay(BUTTON_PRESS_DURATION_MS);

    // Release the virtual button.
    digitalWrite(POWER_BUTTON_PIN, LOW);

    lastPowerButtonPressTime = millis();
}

// =====================================================
// Wi-Fi functions
// =====================================================

void startWifiConnection()
{
    Serial.print("Connecting to Wi-Fi: ");
    Serial.println(WIFI_SSID);

    WiFi.mode(WIFI_STA);
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
}

void maintainWifiConnection()
{
    if (WiFi.status() == WL_CONNECTED)
    {
        return;
    }

    const unsigned long now = millis();

    if (now - lastWifiReconnectAttempt < WIFI_RECONNECT_INTERVAL_MS)
    {
        return;
    }

    lastWifiReconnectAttempt = now;

    Serial.println("Wi-Fi disconnected, reconnecting...");

    WiFi.disconnect();
    WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
}

// =====================================================
// TV network detection
// =====================================================

bool tvRespondsOnPort(uint16_t port)
{
    WiFiClient client;

    Serial.print("Testing TV port ");
    Serial.print(port);
    Serial.print("... ");

    // We only need to establish a TCP connection.
    // No Samsung command is sent to the TV.
    const bool connected =
        client.connect(TV_IP, port, TV_CONNECT_TIMEOUT_MS);

    if (connected)
    {
        Serial.println("responding");
        client.stop();
        return true;
    }

    Serial.println("no response");
    client.stop();
    return false;
}

bool tvRespondsOverNetwork()
{
    if (WiFi.status() != WL_CONNECTED)
    {
        return false;
    }

    // One responding port is enough to consider
    // the TV reachable.
    for (uint16_t port : TV_PORTS)
    {
        if (tvRespondsOnPort(port))
        {
            return true;
        }
    }

    return false;
}

void updateTvStatus()
{
    // A Wi-Fi outage must not be interpreted as the TV
    // being turned off. Otherwise a network problem could
    // accidentally turn off the soundbar.
    if (WiFi.status() != WL_CONNECTED)
    {
        Serial.println("TV check skipped: Wi-Fi unavailable");
        return;
    }

    const bool currentlyReachable = tvRespondsOverNetwork();

    if (currentlyReachable)
    {
        failedTvChecks = 0;

        if (successfulTvChecks < REQUIRED_ON_DETECTIONS)
        {
            successfulTvChecks++;
        }

        if (
            successfulTvChecks >= REQUIRED_ON_DETECTIONS &&
            (!tvStatusKnown || !tvIsOn)
        )
        {
            tvStatusKnown = true;
            tvIsOn = true;

            Serial.println("TV status changed to: ON");
        }
    }
    else
    {
        successfulTvChecks = 0;

        if (failedTvChecks < REQUIRED_OFF_DETECTIONS)
        {
            failedTvChecks++;
        }

        if (
            failedTvChecks >= REQUIRED_OFF_DETECTIONS &&
            (!tvStatusKnown || tvIsOn)
        )
        {
            tvStatusKnown = true;
            tvIsOn = false;

            Serial.println("TV status changed to: OFF");
        }
    }

    if (tvStatusKnown)
    {
        Serial.print("TV: ");
        Serial.print(tvIsOn ? "ON" : "OFF");

        Serial.print(" | Soundbar: ");
        Serial.print(soundbarIsOn() ? "ON" : "OFF");

        Serial.print(" | Managed by TV: ");
        Serial.println(soundbarManagedByTv ? "YES" : "NO");
    }
}

// =====================================================
// Automation logic
// =====================================================

void handleSoundbarAutomation()
{
    // Do nothing until the TV state has been reliably detected.
    if (!tvStatusKnown)
    {
        return;
    }

    const unsigned long now = millis();
    const bool soundbarOn = soundbarIsOn();

    // Check whether an automatic start attempt succeeded.
    if (automaticStartPending)
    {
        if (soundbarOn)
        {
            automaticStartPending = false;

            Serial.println("Automatic soundbar start confirmed");
        }
        else if (
            now - automaticStartAttemptTime >=
            START_CONFIRM_TIMEOUT_MS
        )
        {
            automaticStartPending = false;
            soundbarManagedByTv = false;

            Serial.println("Automatic soundbar start was not confirmed");
        }
    }

    // -------------------------------------------------
    // TV is on
    // -------------------------------------------------

    if (tvIsOn)
    {
        // Start the soundbar only when it is currently off.
        if (
            !soundbarOn &&
            !automaticStartPending &&
            now - lastPowerButtonPressTime >=
                POWER_RETRY_INTERVAL_MS
        )
        {
            // The ESP now owns this soundbar session.
            // It may therefore turn the soundbar off later
            // when the TV turns off.
            soundbarManagedByTv = true;
            automaticStartPending = true;
            automaticStartAttemptTime = now;

            pressSoundbarPowerButton(
                "TV is on and soundbar is off"
            );
        }

        return;
    }

    // -------------------------------------------------
    // TV is off
    // -------------------------------------------------

    // Leave manually started soundbar sessions alone.
    if (!soundbarManagedByTv)
    {
        return;
    }

    // If the ESP started the soundbar for the TV,
    // turn it off when the TV turns off.
    if (
        soundbarOn &&
        now - lastPowerButtonPressTime >=
            POWER_RETRY_INTERVAL_MS
    )
    {
        automaticStartPending = false;

        pressSoundbarPowerButton(
            "TV is off and soundbar was started automatically"
        );

        return;
    }

    // Once GPIO1 confirms that the soundbar is off,
    // release ownership. A later manual start while the TV
    // is off will then remain untouched.
    if (!soundbarOn && !automaticStartPending)
    {
        soundbarManagedByTv = false;

        Serial.println(
            "Automatic soundbar shutdown confirmed"
        );
    }
}

// =====================================================
// Arduino setup and loop
// =====================================================

void setup()
{
    Serial.begin(115200);
    delay(1000);

    // Configure the optocoupler output.
    pinMode(POWER_BUTTON_PIN, OUTPUT);
    digitalWrite(POWER_BUTTON_PIN, LOW);

    // The external voltage divider already pulls
    // this input low while the soundbar is off.
    pinMode(SOUNDBAR_STATUS_PIN, INPUT);

    // Allow an immediate automatic button press after startup.
    lastPowerButtonPressTime =
        millis() - POWER_RETRY_INTERVAL_MS;

    startWifiConnection();

    Serial.println("Soundbar controller started");
}

void loop()
{
    maintainWifiConnection();

    const unsigned long now = millis();

    if (now - lastTvCheckTime >= TV_CHECK_INTERVAL_MS)
    {
        lastTvCheckTime = now;

        updateTvStatus();
        handleSoundbarAutomation();
    }
}